### ISSUE TITLE
Exception: Unsupported version 4.4.0

### ISSUE THREAD

**Issue by 1exx** [alexmontoanelli/uzabbix#6]
When trying to connect to 4.4 I have a error: "Exception: Unsupported version 4.4.0"
App for android, version: 1.5.1

**Comment by alexmontoanelli** [comment]
Working on ...
--
*Alex Montoanelli*
 » Unetvale <http://www.unetvale.com.br>
 » +55 48 3263 8789
 » INOC 53175*100

**Comment by 1exx** [comment]
With last update all work. Thanks
